# Measure Theory

## Part 1

$P(X)$: Power set $X$

Example: the set is $X=\{ a,b \}$, and thus the power set is $p(x)=\{ \varnothing, X, a,b \}$

__Definition__: $\mathcal{A} \subseteq P(X)$ is called a $\sigma$-algebra.

   (a) $\sigma$-algebra at least has two elements, namely empty set and full set: $\varnothing$,$X \in \mathcal{A}$
   
   (b) $A \in \mathcal{A} \rightarrow A^c: \in \mathcal{A}$
   
   (C) $A_i \in \mathcal{A} \rightarrow \cup_{i=1}^\infty A_i \in \mathcal{A}$
   
__$A \in \mathcal{A}$ is called an $\mathcal{A}$-measureable set.
 
 Example of $\sigma$-algebra:
 
(1) $\mathcal{A}= \{ \varnothing, X \}$

(2) $\mathcal{A}= P(X)$

## Part 2

Easy to show:

$\mathcal{A}_i$ $\sigma$-algebra on $X$, $in \in I(index set)$. Then, $\cap \mathcal{A}_i$ is also a $\sigma$-algebra on $X$.

__Definition__: For $M \subseteq P(X)$, there is a smallest $\sigma$-algebra that contains $M$. That is, $\sigma$-algebra is generated by $M$.

$$ \sigma(M):=\cap_{\mathcal{A} \supseteq M}\mathcal{A}$$
Example:

$$X=\{ a, b, c, d\}, M=\{ \{a\}, \{b\}\}$$

Note that, $M$ is not a $\sigma$-algebra yet, and the smallest $\sigma$-algebra containing $M$:

$$\sigma(M)= \{\varnothing, X=\{ a, b, c, d\},\{a\},\{b\},\{a,b\},\{b,c,d\},\{a,c,d\},\{c,d\}\}$$


__Definition__: 

Let $X$ be a topological space

(Let $X$ be a metric space, or let $X$ be a subset of $\mathbb{R}^n$)

$B(X)$ Borel $\sigma$-algebra on $X$: THe $\sigma$-algebra generated by open sets.

$B(X):=\sigma(\Im)$


## Part 3

What is a measure?

A measure is a $\sigma$-algebra. It can be either a power set or a subset. 

__Definition__: 

$(X, \mathcal{A})$ measurable space. $\mathcal{A}$ is the subset of the set $X$.

A map $\mu: \mathcal{A} \rightarrow [0, \infty]$ is called a measure if it satisfies:

(a) $\mu (\varnothing)=0$

(b) $\mu(\cup_{i=1}^\infty A_i)=\sum_{i=1}^\infty \mu(A_i)$ with $A_i \cap A_j = \varnothing$ for all $A_i \in \mathcal{A}$


__Definition__: Measure space $$(X,\mathcal{A}, \mu)$$

Examples:

$X, \mathcal{A}=P(X)$

(a) For $A\in \mathcal{A}$, counting measure: 

$$\begin{cases}  Count(A) & if A \; has\; finite \; elements  \\ \infty & else  \end{cases}$$

Calculation rules in $[0, \infty]$:

(1) $X+\infty := \infty \;\;  for \; X \in [0, \infty]$

(2) $X \cdot\infty := \infty \;\;  for \; X \in (0, \infty]$

(3) $0 \cdot\infty := 0 \;\;  (for \; X \in (0, \infty])in \; most \; cases \; in \; measure \; theory!)$


(b) Dirac measure for $p \in X$

$$\delta_p (A) \begin{cases} 1 &, p \in  A \\ 0 &, else\end{cases}$$


(c) We search a measure on $X=\mathbb{R}^n$

(1) $\mu ([0,1]^n)=1$

(2) $\mu(x+A)=\mu(A)$ for all $x \in \mathbb{R}^n$

